// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTask(arg1) {
  return window['go']['main']['Task']['GetTask'](arg1);
}

export function SaveTask() {
  return window['go']['main']['Task']['SaveTask']();
}

export function SetTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Task']['SetTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}
